trigger:
  branches:
    include:
    - master
pool:
  vmImage: 'ubuntu-latest'

steps:
 - task: TerraformTaskV4@4
   displayName: 'Terraform Init'
   inputs:
     provider: 'aws'
     command: 'init'
     backendServiceAWS: 'terraform-aws'
     backendAWSBucketName: 'taas1s301'
     backendAWSKey: 'tf.tfstate'
 - task: TerraformTaskV4@4
   displayName: 'Terraform Plan'
   inputs:
     provider: 'aws'
     command: 'plan'
     backendServiceAWS: 'terraform-aws'
     backendAWSBucketName: 'taas1s301'
     backendAWSKey: 'tf.tfstate'
     environmentServiceNameAWS: 'terraform-aws'
 - task: TerraformTaskV4@4
   displayName: 'Terraform Apply'
   inputs:
     provider: 'aws'
     command: 'apply'
     backendServiceAWS: 'terraform-aws'
     backendAWSBucketName: 'taas1s301'
     backendAWSKey: 'tf.tfstate'
     environmentServiceNameAWS: 'terraform-aws'